### ISSUE TITLE
Error 500: "authority is required" when requesting token via password

### ISSUE THREAD

**Issue by alb-car** [scc-digitalhub/AAC#225]
AAC 4.x; when requesting token to `/oauth/token` via grant type `password`, this error is returned:
> {
    "error": "server_error",
    "error_description": "authority is required"
}

In AAC's logs, the following appears:

> Caused by: java.lang.IllegalArgumentException: authority is required
	at org.springframework.util.Assert.hasText(Assert.java:289)
	at it.smartcommunitylab.aac.audit.UserAuthenticationFailureEvent.<init>(UserAuthenticationFailureEvent.java:32)
	at it.smartcommunitylab.aac.audit.ExtendedAuthenticationEventPublisher.translateAuthenticationException(ExtendedAuthenticationEventPublisher.java:162)
	at it.smartcommunitylab.aac.audit.ExtendedAuthenticationEventPublisher.publishAuthenticationFailure(ExtendedAuthenticationEventPublisher.java:131)
	at it.smartcommunitylab.aac.core.ExtendedUserAuthenticationManager.auditException(ExtendedUserAuthenticationManager.java:627)
	at it.smartcommunitylab.aac.core.ExtendedUserAuthenticationManager.authenticate(ExtendedUserAuthenticationManager.java:221)
	at it.smartcommunitylab.aac.oauth.token.ResourceOwnerPasswordTokenGranter.getOAuth2Authentication(ResourceOwnerPasswordTokenGranter.java:117)
	at it.smartcommunitylab.aac.oauth.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:66)
	at it.smartcommunitylab.aac.oauth.token.ResourceOwnerPasswordTokenGranter.grant(ResourceOwnerPasswordTokenGranter.java:76)
	at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:40)
	at it.smartcommunitylab.aac.oauth.endpoint.TokenEndpoint.postAccessToken(TokenEndpoint.java:145)

**Comment by matteo-s** [comment]
fix with 6ab9c2b3ba2977f7a0354a2d62a7037736b9adf1
