### ISSUE TITLE
error calling API GET /roles/{realm}

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#258]
AAC hangs tryng to get roles from a realm:

java.lang.IllegalStateException: Ambiguous handler methods mapped for '/api/roles/realm_dipendenti': {public java.util.Collection it.smartcommunitylab.aac.roles.BaseRealmRolesController.getRealmRoles(java.lang.String) throws it.smartcommunitylab.aac.common.NoSuchRealmException, public java.util.Collection it.smartcommunitylab.aac.roles.SpaceRoleApiController.getRoles(java.lang.String) throws java.lang.Exception}
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.lookupHandlerMethod(AbstractHandlerMethodMapping.java:432) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.handler.AbstractHandlerMethodMapping.getHandlerInternal(AbstractHandlerMethodMapping.java:383) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.getHandlerInternal(RequestMappingInfoHandlerMapping.java:125) ~[spring-webmvc-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping.getHandlerInternal(RequestMappingInfoHandlerMapping.java:67) ~[spring-webmvc-5.3.22.jar:5.3.22]

**Comment by gianpaolo-tndigit** [comment]
Fixed in commit 3c091d21: space roles API moved to /api/spaceroles/{subjectId}, so /api/roles/{realm} is no longer ambiguous.
