### ISSUE TITLE
updating / adding identities (SAML or OIDC) by API does not work

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#263]
if you try to use API PUT /users/{realm}/{userId}/identity/{identityUuid} 
to update or to add SAML or OIDC configuration, AAC responds with an error (Whether the configuration is present or not).

Error for SAML is SamlUserIdentity instead for OIDC is OIDCUserIdentity:

org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class it.smartcommunitylab.aac.saml.model.SamlUserIdentity]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `it.smartcommunitylab.aac.saml.model.SamlUserIdentity` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 3, column: 5]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:388) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:343) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver.readWithMessageConverters(AbstractMessageConverterMethodArgumentResolver.java:185) ~[spring-webmvc-5.3.22.jar:5.3.22]

**Comment by matteo-s** [comment]
this will be refactored after #269

**Comment by gianpaolo-tndigit** [comment]
The identity endpoint was replaced by `/users/{realm}/{userId}/account/{uuid}` in commit 0bcfa196 (PR #139), with a polymorphic body (commit 2e88c3df). 
Then commit d6d312fa (PR #419) fixed the "no Creators" deserialization error for OIDC and SAML accounts. 
Verified on 5.x (commit 8e1e25a8). Closing - please reopen if needed.
