### ISSUE TITLE
UI: cannot register a local account to persist your user

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#318]
- branch 4.x

how to reproduce error:

- login with SPID 
- click on +Register user

in the log you find:

2023-02-27 10:13:53.175 DEBUG 10416 --- [nio-8080-exec-9] i.s.aac.core.service.UserAccountService  : get editable user account create
2023-02-27 10:13:53.199 DEBUG 10416 --- [nio-8080-exec-9] i.s.aac.console.ConsoleExceptionHandler  : build response for error: null
2023-02-27 10:13:53.200 ERROR 10416 --- [nio-8080-exec-9] i.s.aac.console.ConsoleExceptionHandler  : error processing request: null
it.smartcommunitylab.aac.common.NoSuchUserException
	at it.smartcommunitylab.aac.core.service.UserAccountService.getResource(UserAccountService.java:407)
	at it.smartcommunitylab.aac.core.service.UserAccountService.getEditableUserAccount(UserAccountService.java:90)
	at it.smartcommunitylab.aac.core.service.UserAccountService$$FastClassBySpringCGLIB$$a1d601cc.invoke(<generated>)

![cannot-persit-account-from-ui](https://user-images.githubusercontent.com/100349014/221523881-a3a8e15c-3482-43df-aa81-854413920663.png)

**Comment by matteo-s** [comment]
Currently not implemented. See #319
