### ISSUE TITLE
error during editing of a client

### ISSUE THREAD

**Issue by gianpaolo-tndigit** [scc-digitalhub/AAC#423]
(using bootstrap-test.yaml as bootstrap configuration)

When you try to edit client test-0000-12345-client aac give you an error:

AAC error log with:

2023-09-14 16:30:35.907 DEBUG 18252 --- [nio-8080-exec-5] i.s.aac.clients.ClientManager            : get authorities for app test-0000-12345-client in realm test
2023-09-14 16:30:35.973 DEBUG 18252 --- [nio-8080-exec-9] i.s.aac.console.ConsoleExceptionHandler  : build response for error: Cannot invoke "org.springframework.jdbc.core.JdbcTemplate.query(String, org.springframework.jdbc.core.RowMapper, Object[])" because "this.jdbcTemplate" is null
2023-09-14 16:30:35.975 ERROR 18252 --- [nio-8080-exec-9] i.s.aac.console.ConsoleExceptionHandler  : error processing request: Cannot invoke "org.springframework.jdbc.core.JdbcTemplate.query(String, org.springframework.jdbc.core.RowMapper, Object[])" because "this.jdbcTemplate" is null
java.lang.NullPointerException: Cannot invoke "org.springframework.jdbc.core.JdbcTemplate.query(String, org.springframework.jdbc.core.RowMapper, Object[])" because "this.jdbcTemplate" is null
	at it.smartcommunitylab.aac.oauth.store.jdbc.AutoJdbcApprovalStore.findClientApprovals(AutoJdbcApprovalStore.java:65)
	at it.smartcommunitylab.aac.clients.ClientManager.getApprovals(ClientManager.java:763)

![image](https://github.com/scc-digitalhub/AAC/assets/100349014/0cbe6084-59d1-4d68-95d1-dd5555d61451)

**Comment by thomaschiozzi-tndigit** [comment]
As of commit 17e843f088345d16ea24f9d9d96453f63bfa619f I am unable to reproduce this Issue

**Comment by gianpaolo-tndigit** [comment]
unreproducible error with version 5.x
